export const INIT_USER = 'INIT_USER';

export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS';
export const INIT_USER_FAILED = 'INIT_USER_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const INIT_BLOG = 'INIT_BLOG';
export const BLOG_FETCH_SUCCESS = 'BLOG_FETCH_SUCCESS';
export const BLOG_FETCH_FAILED = 'BLOG_FETCH_FAILED';
export const BLOG_POST_DELETE = 'BLOG_POST_DELETE';
export const BLOG_POST_UPDATE = 'BLOG_POST_UPDATE';
export const BLOG_POST_CREATE = 'BLOG_POST_CREATE';
export const BLOG_DETAIL_HANDLER = 'BLOG_DETAIL_HANDLER';
